DISCORD_CLIENT_ID:
DISCORD_CLIENT_SECRET:
DISCORD_REDIRECT_URL:

MAIL_USERNAME: email@gmail.com
MAIL_PASSWORD: email@gmail.com password
MAIL_FROM: email@gmail.com
MAIL_PORT: 587
MAIL_SERVER: smtp.gmail.com
MAIL_TLS: True
MAIL_SSL: False
USE_CREDENTIALS: True
VALIDATE_CERTS: True
